### ISSUE TITLE
Add link to results and directions for feedback

### ISSUE THREAD

**Issue by geohci** [geohci/image-similarity-ui#4]
You can see an example of what that might look like here: https://github.com/geohci/wikipedia-topic-model-api/blob/master/templates/diff-tagging.html#L251

Feedback link should point to: https://meta.wikimedia.org/wiki/Research_talk:A_System_for_Large-scale_Image_Similarity

The only other difference is that I've been meaning to change that from a generic `Result link` text (https://github.com/geohci/wikipedia-topic-model-api/blob/master/templates/diff-tagging.html#L161) to actually displaying the URL so it's easier to copy. my initial thought is to add it [between the form and results](https://github.com/geohci/image-similarity-ui/blob/main/templates/index.html#L68-L69) but you might want to play around a little to find a good spot.

**Comment by AniketARS** [comment]
Hi @geohci, I was working on this issue and one problem i faced how can i generate `Result link` url for `POST` Request.

**Comment by geohci** [comment]
> I was working on this issue and one problem i faced how can i generate Result link url for POST Request.

Let me know if I'm misunderstanding but my suggestion would be to generate the link to the UI and not to the API. That way it can just be in the form `https://imagesimilarity.toolforge.org/?image_name=image-name.ext` and the UI will handle the GET vs. POST, formatting etc. This will make it easier to see the example and what the issue is too for us rather than directly inspecting API outputs.

**Comment by geohci** [comment]
Fixed by PR #5 !
