### ISSUE TITLE
Use Toolforge CDNs

### ISSUE THREAD

**Issue by geohci** [geohci/image-similarity-ui#8]
Something to be aware of that I should have mentioned before: when using external libraries on Toolforge (fonts/javascript mainly), there's a Toolforge CDN that we should use because it helps to preserve people's privacy when they use the webapp. it's pretty compehensive so hopefully nothing that you would need that's not on there (and i think there's a process for adding new libraries if necessary). the [alpinejs library](https://github.com/geohci/image-similarity-ui/blob/main/templates/index.html#L144) is available at: https://tools-static.wmflabs.org/cdnjs/ajax/libs/alpinejs/3.10.2/cdn.min.js

More generally:
* Javascript libraries: https://cdnjs.toolforge.org/
* Fonts: https://fontcdn.toolforge.org/
* More details in this blogpost: https://phabricator.wikimedia.org/phame/live/5/post/65/toolforge_provides_proxied_mirrors_of_cdnjs_and_now_fontcdn_for_your_usage_and_user-privacy/

**Comment by AniketARS** [comment]
fixed in Pull Request #9
